# Generated by Django 3.2.9 on 2022-06-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='auction',
            name='Costs',
            field=models.CharField(default='0$', max_length=140),
        ),
    ]
