# Generated by Django 3.2.9 on 2022-06-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20220604_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='image',
            new_name='receipt',
        ),
    ]
